menu:
  Home: /
  Archives: /archives
  Twitter: https://twitter.com/marocchino
  GitHub: https://github.com/marocchino

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 
